-- Testing imported data


-- PLAYERS
SELECT USERNAME, DATE_JOINED, PROFILE_VIEWS, FOLLOWERS, POINTS
    FROM PLAYERS
    ORDER BY FOLLOWERS DESC;
    
SELECT COUNTRY, COUNT(COUNTRY)
    FROM PLAYERS
    GROUP BY COUNTRY
    ORDER BY COUNT(COUNTRY) DESC;

SELECT CITY, COUNT(CITY)
    FROM PLAYERS
    GROUP BY CITY
    ORDER BY COUNT(CITY) DESC;
    
SELECT USERNAME, BLITZ, BULLET, RAPID, ROUND((BLITZ+BULLET+RAPID/3), 3) as Average
    FROM PLAYERS;
    
 SELECT USERNAME, BLITZ, BULLET, RAPID, ROUND((BLITZ+BULLET+RAPID/3), 3) as Average
    FROM PLAYERS
    WHERE (BLITZ+BULLET+RAPID/3) > 1000;

SELECT TITLE, COUNT(TITLE)
    FROM PLAYERS
    GROUP BY TITLE
    ORDER BY COUNT(TITLE) DESC;
    
-- MATCHES

SELECT "FORMAT", COUNT("FORMAT")
    FROM MATCHES
    GROUP BY "FORMAT"
    ORDER BY COUNT("FORMAT") DESC;

SELECT "RESULT", COUNT("RESULT")
    FROM MATCHES
    GROUP BY "RESULT"
    ORDER BY COUNT("RESULT") DESC;

SELECT "FORMAT", "RESULT", COUNT("RESULT")
    FROM MATCHES
    GROUP BY "FORMAT", "RESULT"
    ORDER BY COUNT("RESULT") DESC;
    
-- LEADERBOARDS

SELECT COUNTRY, COUNT(COUNTRY), 
        ROUND(AVG(WORLD_RANK),3), ROUND(AVG(RAPID_RATING),3), 
        ROUND(AVG(BLITZ_RATING),3), ROUND(AVG(CLASSICAL_RATING),3)
    FROM LEADERBOARDS
    GROUP BY COUNTRY
    ORDER BY COUNT(COUNTRY) DESC;

SELECT BIRTHPLACE, COUNT(BIRTHPLACE)
    FROM LEADERBOARDS
    GROUP BY BIRTHPLACE
    ORDER BY COUNT(BIRTHPLACE) DESC;
    
-- JOINS
SELECT l.PLAYER_NAME, p.USERNAME, l.WORLD_RANK, p.BLITZ, l.BLITZ_RATING, l.BIRTHPLACE
    FROM LEADERBOARDS l
    INNER JOIN PLAYERS p ON l.PLAYER_NAME = p.LEGAL_NAME;

SELECT p.USERNAME, ROUND(AVG(m.WHITE_ACCURACY),3), p.FOLLOWERS, p.POINTS
    FROM PLAYERS p
    INNER JOIN MATCHES m ON p.USERNAME = m.WHITE_PLAYER
    GROUP BY p.USERNAME, m.WHITE_PLAYER, p.FOLLOWERS, p.POINTS;

SELECT p.USERNAME, ROUND(AVG(m.BLACK_ACCURACY),3), p.FOLLOWERS, p.POINTS
    FROM PLAYERS p
    INNER JOIN MATCHES m ON p.USERNAME = m.BLACK_PLAYER
    GROUP BY p.USERNAME, m.BLACK_PLAYER, p.FOLLOWERS, p.POINTS;